<?php
require_once '../config/auth.php'; require_role('guru');
$pdo=db(); $gid=(int)user_reference(); $error='';
$q=$pdo->prepare('SELECT DISTINCT j.id_kelas,k.nama_kelas,j.id_mapel,mp.nama_mapel FROM jadwal j JOIN kelas k ON k.id_kelas=j.id_kelas JOIN mata_pelajaran mp ON mp.id_mapel=j.id_mapel WHERE j.id_guru=? ORDER BY k.nama_kelas,mp.nama_mapel');$q->execute([$gid]);$assignments=$q->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf(); $kelas=(int)($_POST['id_kelas']??0);$mapel=(int)($_POST['id_mapel']??0);$nis=trim($_POST['nis']??'');
 $q=$pdo->prepare('SELECT 1 FROM jadwal WHERE id_guru=? AND id_kelas=? AND id_mapel=?');$q->execute([$gid,$kelas,$mapel]);
 $q2=$pdo->prepare('SELECT 1 FROM siswa WHERE nis=? AND id_kelas=?');$q2->execute([$nis,$kelas]);
 $values=[(float)($_POST['nilai_tugas']??-1),(float)($_POST['nilai_uts']??-1),(float)($_POST['nilai_uas']??-1)];
 if(!$q->fetch()||!$q2->fetch()) $error='Siswa atau penugasan tidak berada dalam tanggung jawab Anda.';
 elseif(min($values)<0||max($values)>100) $error='Nilai harus berada di antara 0 dan 100.';
 else{$ta=(int)$pdo->query("SELECT id_tahun_ajaran FROM tahun_ajaran WHERE status='Aktif' LIMIT 1")->fetchColumn();if(!$ta)$error='Belum ada tahun ajaran aktif.';else{$akhir=round(array_sum($values)/3,2);$q=$pdo->prepare('INSERT INTO nilai(nis,id_mapel,id_guru,id_tahun_ajaran,nilai_tugas,nilai_uts,nilai_uas,nilai_akhir) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE nilai_tugas=VALUES(nilai_tugas),nilai_uts=VALUES(nilai_uts),nilai_uas=VALUES(nilai_uas),nilai_akhir=VALUES(nilai_akhir),id_guru=VALUES(id_guru)');$q->execute([$nis,$mapel,$gid,$ta,...$values,$akhir]);flash('success','Nilai berhasil disimpan.');redirect('nilai.php');}}
}
$students=[];foreach($assignments as $a){$q=$pdo->prepare('SELECT nis,nama_siswa FROM siswa WHERE id_kelas=? ORDER BY nama_siswa');$q->execute([$a['id_kelas']]);$students[$a['id_kelas']]=$q->fetchAll();}
$page_title='Input Nilai';require '../includes/header.php';require '../includes/sidebar.php';require '../includes/flash.php';
?><h2>Input / Edit Nilai</h2><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><div class="card p-4 col-xl-8"><form method="post" class="row g-3"><?=csrf_field()?><div class="col-md-6"><label class="form-label">Kelas dan mata pelajaran</label><select class="form-select" id="assignment" required><option value="">Pilih penugasan</option><?php foreach($assignments as $a):?><option value="<?=e($a['id_kelas'].'|'.$a['id_mapel'])?>"><?=e($a['nama_kelas'].' · '.$a['nama_mapel'])?></option><?php endforeach;?></select><input type="hidden" name="id_kelas"><input type="hidden" name="id_mapel"></div><div class="col-md-6"><label class="form-label">Siswa</label><select class="form-select" name="nis" id="student" required disabled><option>Pilih kelas terlebih dahulu</option></select></div><?php foreach(['nilai_tugas'=>'Nilai Tugas','nilai_uts'=>'Nilai UTS','nilai_uas'=>'Nilai UAS'] as $field=>$label):?><div class="col-md-4"><label class="form-label"><?=e($label)?></label><input class="form-control" type="number" name="<?=e($field)?>" min="0" max="100" step="0.01" required></div><?php endforeach;?><div class="col-12"><button class="btn btn-primary">Simpan nilai</button></div></form></div><script>const data=<?=json_encode($students,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP)?>;document.getElementById('assignment').addEventListener('change',function(){let p=this.value.split('|'),s=document.getElementById('student');document.querySelector('[name=id_kelas]').value=p[0]||'';document.querySelector('[name=id_mapel]').value=p[1]||'';s.innerHTML='';(data[p[0]]||[]).forEach(x=>s.add(new Option(x.nama_siswa+' ('+x.nis+')',x.nis)));s.disabled=!p[0]});</script><?php require '../includes/footer.php';
